words = [
     'force',
     'star wars',
     'yoda',
     'kylo ren',
     'luke skywalker',
     'han solo',
     'chewbacca',
     'chewie',
     'bb eight',
     'lightsaber',
     'sith',
     'jar jar binks',
     'anakin skywalker',
     'darth vader',
     'poe dameron',
     'general hux',
     'leia',
     'x wing',
     'millennium falcon',
     'palpatine',
     'galactic empire',
     'first order',
     'tie fighter',
     'death star',
     'star killer',
     'the force awakens',
     'new jedi order',
     'jedi',
     'alderaan',
     'a new hope',
     'return of the jedi',
     'empire strikes back',
     'the phantom menace',
     'tatooine ',
     'amidala',
     'attack of the clones',
     'revenge of the sith',
     'george lucas',
     'anakin skywalker',
     'dantoine',
     'dagobah',
     'the clone wars',
     'battle of jakku',
     'jakku',
     'stormtrooper',
     'sarlak',
     'bobba fett',
     'lando calrissian',
     'clone wars',
     'cloud city',
     'the jedi temple',
     'count dooku',
     'darth tyrannous',
     'coruscant',
     'darth plagueis',
     'jedi',
     'darth sidious',
     'midichlorians',
     'obi wan kenobi',
     'grand moff tarkin',
     'admiral ackbar',
     'alderaan',
     'at at',
     'astromech droid',
     'droid',
     'slave one',
     'aurra sing',
     'bantha',
     'y wing',
     'b wing',
     'bossk',
     'captain phasma',
     'snook',
     'supreme leader snook',
     'cantina band',
     'force lightning',
     'jabba the hutt',
     'jabba',
     'hoth',
     'star destroyer',
     'kit fisto',
     'mandalorian',
     'mon mothma',
     'mon calamari',
     'mustafar',
     'naboo',
     'nien nunb',
     'rancor',
     'padme amidala',
     'sand trooper',
     'snow speeder',
     'blaster',
     'wampa',
     'lor san tekka',
     'maz kanata',
     'starkiller base',
     'takodana',
     'guavian death gang',
     'kanjiklub gang',
     'supreme leader snoke',
     'rathtars',
     'unkar plutt'
 ]
